openapi: 3.1.0
info:
  title: Expected data contracts for the dynamic frontend
  description: This spec outlines the contracts a backend server must fulfill for the Application to run against it
  version: 1.0.0
paths:
  /bootstrap.json:
    get:
      summary: Retrieve the bootstrap resource for this site
      description: |-
        This endpoint is called by the front end upon loading to bootstrap the application. The application is hardcoded to load this from its in base address. Its recommended this endpoint is serviced by adding a json file called bootstrap.json into the html root alongside other static assets.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bootstrap'
  
  /config:
    get:
      summary: Retrieve the main configuration resource for loading the site
      description: |-
        This endpoint will return the main configuration for loading the dynamic site. Refer to the schema at the bottom for what needs to be contained
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
  /actions/{type}/{actionName}:
    post:
      parameters:
        - name: type
          in: path
          description: ID of order that needs to be fetched
          required: true
          schema:
            type: string
        - name: actionName
          in: path
          description: ID of order that needs to be fetched
          required: true
          schema:
            type: string
  /details/{type}/{id}:
    get:
      parameters:
        - name: type
          in: path
          description: ID of order that needs to be fetched
          required: true
          schema:
            type: string
        - name: id
          in: path
          description: ID of order that needs to be fetched
          required: true
          schema:
            type: string
  /table/{type}:
    get:
      parameters:
        - name: type
          in: path
          description: ID of order that needs to be fetched
          required: true
          schema:
            type: string
  /field/{fieldName}:
    get:
      parameters:
        - name: fieldName
          in: path
          description: ID of order that needs to be fetched
          required: true
          schema:
            type: string
components:
  schemas:
    Actions:
      type: array
      items: 
        type: object
        properties:
          name:
          displayName:
          fields:
            type: array
            items:
              type: object
              properties:
                name:
                displayName:
                preset:
    Bootstrap:
      type: object
      properties:
        basepath:
          type: string
          description: This is the url with which to base all following api calls on. 
      required:
        - basepath
    Config:
      type: object
      properties:
        routes:
          description: list of base routes to load in the site navigation  bar alongside home
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                description: One of 'table' or 'frame' depending if the page is for loading an iframe or a datatable
              tableKey:
                type: string
                description: required for type == 'table' and points to which type of data this page is meant to load a table for
              name:
                type: string
                description: required for type == 'frame'. used to build the url for the page and should be all lower case and url safe
              displayName:
                type: string
                description: required for type == 'frame'. The display text for the navigation item
              url:
                type: string
                description: required for type == 'frame'. The url used to load in the iframe
            required:
              - type
        types: 
          type: object
          description: Defines the schemas, relations and actions for all the types the site should be able to render. This is a hashmap of type name to properties for the type. This documentation contains an example type.
          properties:
            exampleType:
              type: object
              properties:
                displayName:
                  type: string
                properties:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      displayName:
                        type: string
                      summary:
                        type: boolean
                      filterable:
                        type: boolean
                      link:
                        type: object
                        properties:
                          type:
                            type: string
                          dataType:
                            type: string
                          targetField:
                            type: string
        actions: 
          $ref: '#/components/schemas/Actions'
        tableActions:
          $ref: '#/components/schemas/Actions'

        
      
